import { useState, useEffect } from 'react';
import type { AnalysisResult, FounderInput, Decision } from '../types';
import confetti from 'canvas-confetti';

interface Props {
  result: AnalysisResult;
  formData: FounderInput;
  decision: Decision;
  onDecision: (d: Decision) => void;
  onReAnalyze: (revised: string) => void;
  onBackToStart: () => void;
}

const DECISION_CARDS: {
  id: Decision;
  icon: JSX.Element;
  label: string;
  description: string;
  color: string;
  bg: string;
  borderColor: string;
}[] = [
  {
    id: 'proceed',
    icon: (
      <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#10B981" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14" />
        <polyline points="22 4 12 14.01 9 11.01" />
      </svg>
    ),
    label: 'PROCEED',
    description: "I've validated enough to move forward with confidence.",
    color: '#10B981',
    bg: '#ECFDF5',
    borderColor: '#10B981',
  },
  {
    id: 'pivot',
    icon: (
      <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#F59E0B" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <polyline points="23 4 23 10 17 10" />
        <path d="M20.49 15a9 9 0 1 1-2.12-9.36L23 10" />
      </svg>
    ),
    label: 'PIVOT',
    description: 'I need to change a key assumption or constraint before proceeding.',
    color: '#F59E0B',
    bg: '#FFFBEB',
    borderColor: '#F59E0B',
  },
  {
    id: 'pause',
    icon: (
      <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#6B7280" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <circle cx="12" cy="12" r="10" />
        <line x1="12" y1="8" x2="12" y2="12" />
        <line x1="12" y1="16" x2="12.01" y2="16" />
      </svg>
    ),
    label: 'PAUSE',
    description: 'I need more information before making a decision.',
    color: '#6B7280',
    bg: '#F3F4F6',
    borderColor: '#6B7280',
  },
];

export default function Screen3Decision({
  result,
  formData,
  decision,
  onDecision,
  onReAnalyze,
  onBackToStart,
}: Props) {
  const [checks, setChecks] = useState([false, false, false]);
  const [pivotText, setPivotText] = useState('');

  useEffect(() => {
    if (decision === 'proceed') {
      setChecks([false, false, false]);
    }
  }, [decision]);

  const handleCheck = (idx: number) => {
    const next = [...checks];
    next[idx] = !next[idx];
    setChecks(next);

    if (next.every(Boolean)) {
      confetti({
        particleCount: 120,
        spread: 80,
        origin: { y: 0.5 },
        colors: ['#2563EB', '#10B981', '#F59E0B'],
      });
    }
  };

  const allChecked = checks.every(Boolean);

  const now = new Date();
  const timestamp = now.toLocaleDateString('en-US', {
    month: 'long',
    day: 'numeric',
    year: 'numeric',
    hour: 'numeric',
    minute: '2-digit',
  });

  const handleDownload = () => {
    const plan = [
      'FOUNDER SECOND BRAIN — ANALYSIS OUTPUT',
      '======================================',
      `Idea: ${formData.idea}`,
      `Background: ${formData.background}`,
      `Customer: ${formData.customer}`,
      `Budget: ${formData.budget}`,
      `Timeline: ${formData.timeline}`,
      '',
      `Pattern Match Score: ${result.confidence_score}/20`,
      '',
      'Patterns Used:',
      ...result.patterns.map((p, i) => `  ${i + 1}. ${p.name} (score: ${p.score})`),
      '',
      'AI Analysis:',
      `Clarified Idea: ${result.clarified_idea}`,
      `Assumptions: ${result.assumptions}`,
      `Failure Risk: ${result.failure_risk}`,
      `Milestone Plan: ${result.milestone_plan}`,
      `First Step: ${result.first_step}`,
      '',
      'Generated by Founder Second Brain — USAII Hackathon 2026',
    ].join('\n');

    const blob = new Blob([plan], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'founder_plan.txt';
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="animate-fadeIn">
      {/* Page Header */}
      <div style={{ marginBottom: '32px' }}>
        <h1
          style={{
            fontSize: '28px',
            fontWeight: 700,
            color: '#111827',
            letterSpacing: '-0.03em',
            marginBottom: '8px',
          }}
        >
          What is your next move?
        </h1>
        <p style={{ fontSize: '15px', color: '#6B7280' }}>
          You've reviewed the analysis. Now it's your turn to decide.
        </p>
      </div>

      {/* Three Decision Cards */}
      <div
        style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(3, 1fr)',
          gap: '16px',
          marginBottom: '32px',
        }}
      >
        {DECISION_CARDS.map((card) => {
          const selected = decision === card.id;
          return (
            <button
              key={card.id}
              onClick={() => onDecision(card.id)}
              style={{
                background: '#FFFFFF',
                border: `2px solid ${selected ? card.color : '#E5E7EB'}`,
                borderRadius: '16px',
                padding: '24px 20px',
                cursor: 'pointer',
                textAlign: 'left',
                transition: 'all 0.2s ease',
                boxShadow: selected
                  ? `0 0 0 1px ${card.color}, 0 4px 12px rgba(0,0,0,0.05)`
                  : '0 1px 3px rgba(0,0,0,0.03)',
                transform: selected ? 'translateY(-2px)' : 'none',
              }}
            >
              <div style={{ marginBottom: '16px' }}>{card.icon}</div>
              <p
                style={{
                  fontSize: '20px',
                  fontWeight: 700,
                  color: selected ? card.color : '#111827',
                  marginBottom: '8px',
                  letterSpacing: '-0.01em',
                }}
              >
                {card.label}
              </p>
              <p
                style={{
                  fontSize: '13px',
                  color: '#6B7280',
                  lineHeight: 1.5,
                }}
              >
                {card.description}
              </p>
            </button>
          );
        })}
      </div>

      {/* Decision Flows */}

      {decision === 'proceed' && (
        <div className="card-static animate-slideUp" style={{ borderColor: '#A7F3D0' }}>
          <div style={{ textAlign: 'center', marginBottom: '20px' }}>
            <p
              style={{
                fontSize: '15px',
                fontWeight: 600,
                color: '#111827',
                marginBottom: '4px',
              }}
            >
              Confirm Your Readiness
            </p>
            <p style={{ fontSize: '13px', color: '#6B7280' }}>
              Check each box to confirm you're ready to proceed
            </p>
          </div>

          <div
            style={{
              display: 'flex',
              flexDirection: 'column',
              gap: '10px',
              maxWidth: '480px',
              margin: '0 auto 24px',
            }}
          >
            {[
              'I have identified my first real customer to contact',
              'I understand the primary failure risk in my context',
              'I have a clear action for the next 48 hours',
            ].map((label, i) => (
              <label
                key={i}
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  gap: '12px',
                  padding: '14px 16px',
                  borderRadius: '10px',
                  background: checks[i] ? '#ECFDF5' : '#F9FAFB',
                  border: `1px solid ${checks[i] ? '#A7F3D0' : '#E5E7EB'}`,
                  cursor: 'pointer',
                  transition: 'all 0.15s ease',
                }}
              >
                <input
                  type="checkbox"
                  checked={checks[i]}
                  onChange={() => handleCheck(i)}
                  style={{
                    width: '20px',
                    height: '20px',
                    accentColor: '#10B981',
                    cursor: 'pointer',
                  }}
                />
                <span
                  style={{
                    fontSize: '14px',
                    fontWeight: 500,
                    color: checks[i] ? '#065F46' : '#111827',
                    lineHeight: 1.4,
                  }}
                >
                  {label}
                </span>
              </label>
            ))}
          </div>

          {allChecked && (
            <div
              className="animate-scaleIn"
              style={{
                textAlign: 'center',
                padding: '20px',
                background: '#ECFDF5',
                borderRadius: '12px',
                border: '1px solid #A7F3D0',
              }}
            >
              <p
                style={{
                  fontSize: '17px',
                  fontWeight: 700,
                  color: '#065F46',
                  marginBottom: '12px',
                }}
              >
                ✅ You are cleared to proceed
              </p>
              <button
                onClick={handleDownload}
                className="btn-primary"
                style={{
                  background: '#10B981',
                  height: '44px',
                  padding: '0 24px',
                }}
              >
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
                  <polyline points="7 10 12 15 17 10" />
                  <line x1="12" y1="15" x2="12" y2="3" />
                </svg>
                Download Your Plan
              </button>
            </div>
          )}
        </div>
      )}

      {decision === 'pivot' && (
        <div className="card-static animate-slideUp" style={{ borderColor: '#FDE68A' }}>
          <div style={{ marginBottom: '16px' }}>
            <p
              style={{
                fontSize: '15px',
                fontWeight: 600,
                color: '#111827',
                marginBottom: '4px',
              }}
            >
              What will you change?
            </p>
            <p style={{ fontSize: '13px', color: '#6B7280' }}>
              Describe your revised approach and we'll re-analyze with the new constraint
            </p>
          </div>

          <textarea
            className="input-field"
            rows={4}
            placeholder="e.g. Instead of targeting all small businesses, I will focus only on restaurants in a single neighborhood. Or: I will reduce scope to a software-only solution without owning vehicles."
            value={pivotText}
            onChange={(e) => setPivotText(e.target.value)}
            style={{ minHeight: '120px', marginBottom: '16px' }}
          />

          <button
            onClick={() => onReAnalyze(pivotText)}
            disabled={!pivotText.trim()}
            className="btn-primary"
            style={{
              width: '100%',
              height: '44px',
              background: pivotText.trim() ? '#F59E0B' : undefined,
            }}
          >
            Re-Analyze with New Constraint →
          </button>
        </div>
      )}

      {decision === 'pause' && (
        <div className="card-static animate-slideUp" style={{ borderColor: '#E5E7EB' }}>
          <div
            style={{
              display: 'flex',
              alignItems: 'flex-start',
              gap: '14px',
            }}
          >
            <div
              style={{
                width: '40px',
                height: '40px',
                borderRadius: '10px',
                background: '#F3F4F6',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                flexShrink: 0,
              }}
            >
              <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="#6B7280" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <circle cx="12" cy="12" r="10" />
                <line x1="12" y1="8" x2="12" y2="12" />
                <line x1="12" y1="16" x2="12.01" y2="16" />
              </svg>
            </div>
            <div>
              <p
                style={{
                  fontSize: '16px',
                  fontWeight: 600,
                  color: '#111827',
                  marginBottom: '4px',
                }}
              >
                Analysis saved
              </p>
              <p
                style={{
                  fontSize: '13px',
                  color: '#9CA3AF',
                  marginBottom: '10px',
                }}
              >
                Analyzed on {timestamp}
              </p>
              <p
                style={{
                  fontSize: '14px',
                  color: '#6B7280',
                  lineHeight: 1.6,
                }}
              >
                The patterns don't change. Your thinking might. Return when you're ready.
              </p>
            </div>
          </div>
        </div>
      )}

      {/* Back to Start */}
      <div style={{ textAlign: 'center', marginTop: '24px' }}>
        <button className="btn-secondary" onClick={onBackToStart} style={{ fontSize: '13px' }}>
          ← Start a New Analysis
        </button>
      </div>
    </div>
  );
}
